[package]
name = "tiaview"
version = "0.1.0"
authors = ["Jonathan Perret <j-github@jonathanperret.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.1"

